### ISSUE TITLE
Crash when using VCS URLs

### ISSUE THREAD

**Issue by dan-passaro** [Deepwalker/pundler#17]
Pundler seems to crash when using a VCS URL.  See:

```
$ pip freeze | grep pundle
You are using pip version 6.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pundle==0.5.3
$ cat requirements.txt 
Django~=1.4.0
git+https://github.com/GoodCloud/django-longer-username.git@e4e85d7d29b2ba4fdd7937aa76c02e0098516406#egg=longerusername-dev
$ python -m pundle install
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 744, in <module>
    CmdRegister.main()
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 612, in main
    cls.commands[alias]()
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 618, in cmd_install
    install_all(**create_parser_or_exit())
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 494, in install_all
    suite = Parser(*a, **kw).create_suite()
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 398, in create_suite
    reqs, freezy, diry = self.parse_requirements(), self.parse_frozen(), self.parse_directory()
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 434, in parse_requirements
    return dict((req.key, req) for req in (CustomReq(line, 'requirements file') for line in requirements))
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 434, in <genexpr>
    return dict((req.key, req) for req in (CustomReq(line, 'requirements file') for line in requirements))
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 434, in <genexpr>
    return dict((req.key, req) for req in (CustomReq(line, 'requirements file') for line in requirements))
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 112, in __init__
    res = parse_vcs_requirement(line)
  File "/home/dpassaro/.local/lib/python2.7/site-packages/pundle.py", line 68, in parse_vcs_requirement
    parsed_url = urlparse(url)
TypeError: 'module' object is not callable
```

Commenting out the VCS entry (2nd line) of requirements.txt allows `python -m pundle install` to execute.

**Comment by Deepwalker** [comment]
Seems like py2 compatibility issue. Busy right now, will look in two days.

**Comment by Deepwalker** [comment]
I have fixed issue. Try 0.5.5
