### ISSUE TITLE
Pundler doesn't support pip 10

### ISSUE THREAD

**Issue by orsinium** [Deepwalker/pundler#24]
```
File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 235, in locate_and_install
    raise PundleException('%s was not installed due error %s' % (self.egg or loc_dist.name, exc))
__main__.PundleException: Jinja2 was not installed due error module 'pip' has no attribute 'main'
```

In pip 10 function `main` has been moved into `pip._internal`.

**Comment by Deepwalker** [comment]
Try 0.9.0.

**Comment by Deepwalker** [comment]
Did it work for you?

**Comment by orsinium** [comment]
I don't want downgrade pip. In 10 version pip [switches to new pypi](https://pip.pypa.io/en/stable/news/) and adds so many useful features. I'm recommend you update your pip too:
```
pip install -U pip
```

If you plan maintain pundler and fix this problem with backward compatibility I'm recommend use try-except construction like here:
https://github.com/orsinium/install-requires/blob/master/install_requires/core.py#L2

**Comment by Deepwalker** [comment]
I mean try pundle==0.9.0

**Comment by orsinium** [comment]
```
$ pundle 
Install some packages
try <pip._vendor.distlib.locators.SimpleScrapingLocator object at 0x7fe791119278> for pytest==2.9.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 226, in locate_and_install
    pip.main([
AttributeError: module 'pip' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pundle", line 11, in <module>
    sys.exit(CmdRegister.main())
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 811, in main
    cls.commands[alias]()
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 817, in cmd_install
    install_all(**create_parser_or_exit())
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 696, in install_all
    suite.install()
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 450, in install
    state.reveal_requirements(self, install=install)
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 310, in reveal_requirements
    dist = self.check_installed_version(suite, install=install)
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 281, in check_installed_version
    dist = self.requirement.locate_and_install(suite, installed=self.get_installed())
  File "/usr/local/lib/python3.5/dist-packages/pundle.py", line 235, in locate_and_install
    raise PundleException('%s was not installed due error %s' % (self.egg or loc_dist.name, exc))
pundle.PundleException: pytest was not installed due error module 'pip' has no attribute 'main'

$ pip list
Package    Version
---------- -------
pip        10.0.1 
pundle     0.9.0  
setuptools 39.2.0 
wheel      0.31.1 
```

**Comment by Deepwalker** [comment]
There is no such line in 0.9.0. Please, recheck your setup. This trace is from old version.

**Comment by orsinium** [comment]
Yes, it's ok, I see right imports in pundler 0.9. But what about latest pundler version?

**Comment by Deepwalker** [comment]
It is latest https://pypi.org/project/pundle/
I mean does latest 0.9.0 solve your problem? If all ok, I will close issue.
Thank you for reporting! pip are not aware about pundle that uses its internals :) So we need to upgrade it time to time.

**Comment by orsinium** [comment]
Good. Thank you for response.
