### ISSUE TITLE
`pundle install` generates invalid filename on Windows

### ISSUE THREAD

**Issue by eight04** [Deepwalker/pundler#29]
It seems that pundler is using a filename containing `:` that is invalid on Windows:
```
OSError: [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'C:\\Users\\Ow
ner\\AppData\\Local\\Temp\\tmp7gjjfpuk\\bin' -> 'C:\\Users\\Owner\\.pundledir\\C
Python-3.7.1-v3.7.1:260ec2c36a\\livereload-2.5.2\\bin'
```

Windows 7 x64
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
pundle     0.9.1

<details>
<summary>Full log</summary>

```
D:\Dev\comiccrawler>pundle install
Install some packages
try <pip._vendor.distlib.locators.SimpleScrapingLocator object at 0x000000000308
3CF8> for livereload<3,>=2.5.2
Collecting livereload==2.5.2 from https://files.pythonhosted.org/packages/dd/b4/
213daced3ff1b4e02a1f700748e20e9a7481f5bfef57d11ae9babfd4aa2f/livereload-2.5.2-py
2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/dd/b4/213daced3ff1b4e02a1
f700748e20e9a7481f5bfef57d11ae9babfd4aa2f/livereload-2.5.2-py2.py3-none-any.whl
Installing collected packages: livereload
Successfully installed livereload-2.5.2
Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python37\lib\shutil.py", li
ne 557, in move
    os.rename(src, real_dst)
OSError: [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'C:\\Users\\Ow
ner\\AppData\\Local\\Temp\\tmp7gjjfpuk\\bin' -> 'C:\\Users\\Owner\\.pundledir\\C
Python-3.7.1-v3.7.1:260ec2c36a\\livereload-2.5.2\\bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 246, in locate_and_install
    shutil.move(op.join(tmp_dir, item), op.join(target_dir, item))
  File "c:\users\owner\appdata\local\programs\python\python37\lib\shutil.py", li
ne 568, in move
    symlinks=True)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\shutil.py", li
ne 315, in copytree
    os.makedirs(dst)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\os.py", line 2
11, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\os.py", line 2
11, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\os.py", line 2
21, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] 目錄名稱無效。: 'C:\\Users\\Owner\\.pundledir
\\CPython-3.7.1-v3.7.1:260ec2c36a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python37\lib\runpy.py", lin
e 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\runpy.py", lin
e 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\Scripts\pundle.exe
\__main__.py", line 9, in <module>
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 1025, in main
    cls.commands[alias]()
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 1031, in cmd_install
    install_all(**create_parser_or_exit())
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 908, in install_all
    suite.install()
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 467, in install
    state.reveal_requirements(self, install=install)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 327, in reveal_requirements
    dist = self.check_installed_version(suite, install=install)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 298, in check_installed_version
    dist = self.requirement.locate_and_install(suite, installed=self.get_install
ed())
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\
pundle.py", line 248, in locate_and_install
    raise PundleException('%s was not installed due error %s' % (self.egg or loc
_dist.name, exc))
pundle.PundleException: livereload was not installed due error [WinError 267] 目
錄名稱無效。: 'C:\\Users\\Owner\\.pundledir\\CPython-3.7.1-v3.7.1:260ec2c36a'
```
</details>

**Comment by Deepwalker** [comment]
Fixed in 0.9.2.

**Comment by Deepwalker** [comment]
Did it fix your issue?

**Comment by eight04** [comment]
I'm not sure. I have switched to [vpip](https://pypi.org/project/vpip/).
